version: '3.1'

services:

  order-db:
    image: debezium/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: order_service
      POSTGRES_DB: cafe_order
    ports:
      - 10001:5432


  payment-db:
    image: debezium/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: payment_service
      POSTGRES_DB: cafe_payment
    ports:
      - 10002:5432


  kitchen-db:
    image: debezium/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: kitchen_service
      POSTGRES_DB: cafe_kitchen
    ports:
      - 10003:5432

  delivery-db:
    image: debezium/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: delivery_service
      POSTGRES_DB: cafe_delivery
    ports:
      - 10004:5432


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  debezium:
    image: 'debezium/connect'
    environment:
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      HOST_NAME: 'debezium'
      BOOTSTRAP_SERVERS: 'kafka:9092'
      CONFIG_STORAGE_TOPIC: 'my_connect_configs'
      OFFSET_STORAGE_TOPIC: 'my_connect_offsets'
      STATUS_STORAGE_TOPIC: 'my_connect_statuses'
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - order-db
      - payment-db
      - kitchen-db

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - 9411:9411

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local